### ISSUE TITLE
Overlay sometimes triggers with only one finger

### ISSUE THREAD

**Issue by thopedam** [ivofernandes/pinch_zoom_release_unzoom#1]
Sometimes the overlay is triggered with one finger only, which leads to weird scrolling behavior.

This can be fixed by adding 
```
if (details.pointerCount != 2) return;
```
to `onInteractionStart`

**Comment by ivofernandes** [comment]
Amazing, thanks! Will test it  :)

**Comment by ivofernandes** [comment]
Okay I guess is fixed :) thanks for the feedback :)

**Comment by ivofernandes** [comment]
Which phone did you use for this test?

**Comment by thopedam** [comment]
It was an iPhone X and an iPhone 12 Pro
