### ISSUE TITLE
Nullable type OverlayState

### ISSUE THREAD

**Issue by ghost** [ivofernandes/pinch_zoom_release_unzoom#4]
Hi, in version 0.0.12 i can't build mi app becasuse there is a OverlayState variable that should be nullable 
![image](https://user-images.githubusercontent.com/85644339/217579048-63dc7885-bd2a-4d6c-a5f9-25c82e636792.png)
if i change it locally it works

**Comment by ivofernandes** [comment]
Can you check your flutter doctor? I guess you are missing some flutter upgrade, now the flutter overlay is not nullable anymore.

You can also try to use the version 0.0.10 of this package if you can't upgrade flutter

**Comment by ghost** [comment]
My bad, i was working with flutter 3.3.2, thanks for your time

**Comment by ivofernandes** [comment]
I guess it's also my fault, maybe I should start to care more about how I version packages to avoid this errors, maybe if it was 0.1.0 it would not be automatic to update?

**Comment by ghost** [comment]
As far as I know, Flutter is only upgraded via the `flutter upgrade` command, and not automatically, but packages are installed by default with the `^` flag, and thats the problem, Flutter download the latest version of your package but the Flutter version still outdated
