### ISSUE TITLE
Pinch zoom does not work if the element is inside the ScrollablePositionedList

### ISSUE THREAD

**Issue by StigUK** [ivofernandes/pinch_zoom_release_unzoom#5]
I have a problem when the widget is inside the ScrollablePositionedList (https://pub.dev/packages/scrollable_positioned_list), the zoom does not work. It works perfectly when using the usual ListView.builder. 

Here is my code:

` final List<Widget> widgets = List.generate(100,`
`      (index) => const PinchZoomReleaseUnzoomWidget(`
`        child: FlutterLogo(`
`          size: 100,`
`        ),`
`      ),`
`    );`
`  return ScrollablePositionedList.builder(`
`      itemCount: widgets.length,`
`      itemBuilder: (BuildContext context, int index) => widgets[index],`
`    );`

When I change the Scrollable to a default ListView.builder, everything will work. However, I specifically need a ScrollablePositionedList.

**Comment by ivofernandes** [comment]
Have no idea why, never tried that specific use case

Maybe you can do a PR with this use case in the example file?

https://github.com/ivofernandes/pinch_zoom_release_unzoom/blob/master/example/lib/main.dart

**Comment by StigUK** [comment]
@ivofernandes While I was doing the example, everything worked :)
Most likely the problem was solved after I changed the version of the library from 0.3.5 to 0.3.8. I'm not sure about this. Very strange, but now everything works.
Excuse my disturbing you.

**Comment by StigUK** [comment]
I understand. The problem was most likely that I was trying to zoom in on the top right and bottom corners of the image (widget). In my case, the list was creeping a bit instead of zooming the widget. If you zoom in on the top left and bottom right corners, then everything works.

**Comment by ivofernandes** [comment]
No problem at all :) if you want you can PR that example change you did, maybe the problem was that the scroll event was overriding the scale? For that you can use the twoFingersOn param to avoid scroll when the user has two fingers on the screen

**Comment by StigUK** [comment]
Yes, using twoFingersOn has greatly improved usability. Thanks for that. Also I created [PR](https://github.com/ivofernandes/pinch_zoom_release_unzoom/pull/6) with sample of code.

**Comment by ivofernandes** [comment]
Amazing :) thanks

**Comment by qpalzm963** [comment]
pinch_zoom_release_unzoom: 1.0.0
same question in android
