### ISSUE TITLE
[feature] Overlay.of let us use useRootNavigator

### ISSUE THREAD

**Issue by EArminjon** [ivofernandes/pinch_zoom_release_unzoom#7]
As a developer, i want to use useRootNavigator when my overlay is launched from a nested root.

**Comment by ivofernandes** [comment]
Not really sure what you mean, can you update the example application by adding one more bottom navigation item to reproduce that bug?

**Comment by EArminjon** [comment]
Overlay.of(context) can use the root navigator inside it's property. Can you expose it to let us (developers) use it ?

**Comment by EArminjon** [comment]
It's not a bug :). Just a property to expose.

**Comment by ivofernandes** [comment]
What you want is that pinch to zoom exposes a function that is called when the zoom starts? Maybe the twoFingersOn  function would also do the same?

**Comment by EArminjon** [comment]
As a developer I want the possibility to put rootOverlay at true 
<img width="328" alt="Capture d’écran 2024-01-15 à 09 28 50" src="https://github.com/ivofernandes/pinch_zoom_release_unzoom/assets/37028599/a5dd48b4-a1f6-41f3-aa0e-d770ecd144e7">

**Comment by EArminjon** [comment]
That allow developer to put overlay in the first plan when overlay.of(context) is call from a nested navigation route.

**Comment by ivofernandes** [comment]
Oh I see, do you can run the example application in your machine? Will you create the PR with that change? 

It makes some sense for me to pass that parameter, but I really don't know your use case and I don't know what is the test that should be added to the example application to test if it works fine or not
