### ISSUE TITLE
[bug] New release + Clean code

### ISSUE THREAD

**Issue by EArminjon** [ivofernandes/pinch_zoom_release_unzoom#8]
I don't think recreating the controller inside the build method is a good idea in term of performance or side effect. It prevent some dispose() calls.

<img width="736" alt="Capture d’écran 2024-01-08 à 09 59 28" src="https://github.com/ivofernandes/pinch_zoom_release_unzoom/assets/37028599/b1dcac06-fe70-413f-a38f-9bfacb4618d8">

Also, on master the code seems to be different. 
Maybe a release is missing on pubspec.

**Comment by ivofernandes** [comment]
I guess I updated just to be able to run in my machine, it's convenient to you if I update?

If you want to improve the code create a PR with the changes you want, would be great :)

**Comment by ivofernandes** [comment]
Just updated with your change, thank you so much 👍 

  pinch_zoom_release_unzoom: ^1.0.2
